#!/usr/bin/env bash
# .claude/hooks/update-state.sh
# PostToolUse hook: regenerates STATE.md after every Bash tool call.
#
# B-003 Option E (cycle 8, 2026-05-26) replaced this script's prior
# "amend STATE.md into the just-made commit" model with the much simpler
# "STATE.md is gitignored, regenerate it on disk only" model. The historical
# rationale for amending — making commit history reflect repository state —
# was already leaky (B-002 stale-by-one: STATE.md inside any commit was one
# SHA behind because it was generated pre-amend) AND produced B-003 (compound
# `git commit && git push` left local diverged from origin because the hook
# fired after the push). Option E retires both failure modes by accepting
# that STATE.md is purely-local informational state; it never enters commits
# again. See `docs/B-003-design-exploration.md` for the full analysis.
#
# Behavior:
# - Runs on every PostToolUse:Bash tool call.
# - Skip-perf gate: exits early if HEAD hasn't moved since last run AND
#   STATE.md still exists on disk. Marker stored at
#   `.claude/hooks/.last-state-head` (gitignored).
# - On a HEAD move (commit, reset, checkout, rebase, etc.), regenerates
#   STATE.md from current git state + mailbox cursors.
# - STATE.md is gitignored; this hook never touches git history.
#
# This hook is configured via `.claude/settings.local.json`'s PostToolUse:Bash
# matcher.

set -euo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0

MARKER=".claude/hooks/.last-state-head"
CURRENT=$(git rev-parse HEAD 2>/dev/null || exit 0)
LAST=$(cat "$MARKER" 2>/dev/null || echo "")

# Perf: skip regen if HEAD hasn't moved AND STATE.md exists on disk.
# Mid-session mailbox writes won't refresh STATE.md until the next HEAD
# move, but mailbox surfacing is mostly used at session-start (Rule #8
# awareness gate), which always reads the file fresh after a fresh HEAD.
if [ "$CURRENT" = "$LAST" ] && [ -f STATE.md ]; then
  exit 0
fi

HEAD_SHA="$CURRENT"
HEAD_SUBJECT=$(git log -1 --format='%s' HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
AHEAD=$(git rev-list --count "origin/${BRANCH}..HEAD" 2>/dev/null || echo "?")
BEHIND=$(git rev-list --count "HEAD..origin/${BRANCH}" 2>/dev/null || echo "?")

WT_LINES=$(git status --porcelain 2>/dev/null | head -5)
if [ -z "$WT_LINES" ]; then
  WT_STATE="clean"
else
  WT_STATE=$(printf "dirty:\n%s" "$WT_LINES")
fi

# Smoke + pytest from latest commit body (cheaper than re-running, and the
# commit body is the truth at commit time; if the working tree has drifted
# since, both fields explicitly suggest manual re-run).
SMOKE_LINE=$(git log -1 --format='%B' HEAD | grep -E "ci_smoke\.py" -A1 | tail -1 || true)
if echo "$SMOKE_LINE" | grep -q "OK"; then
  SMOKE_RESULT="OK (per commit body)"
elif echo "$SMOKE_LINE" | grep -qE "FAIL|error"; then
  SMOKE_RESULT="FAIL (per commit body)"
else
  SMOKE_RESULT="unknown (not in commit body; re-run manually)"
fi

PYTEST_LINE=$(git log -1 --format='%B' HEAD | grep -Eo '[0-9]+ passed, [0-9]+ skipped(, [0-9]+ failed)?' | head -1 || true)
[ -z "$PYTEST_LINE" ] && PYTEST_LINE="(not in commit body; re-run manually for ground truth)"

# Mailbox unread counts
UNREAD_DIR=0
UNREAD_OP=0
if [ -d "coordination/mailbox/sent" ]; then
  if [ -f "coordination/mailbox/seen/director.txt" ]; then
    UNREAD_DIR=$(find coordination/mailbox/sent -type f -name '*.md' -newer coordination/mailbox/seen/director.txt 2>/dev/null | wc -l | tr -d ' ')
  fi
  if [ -f "coordination/mailbox/seen/operator.txt" ]; then
    UNREAD_OP=$(find coordination/mailbox/sent -type f -name '*.md' -newer coordination/mailbox/seen/operator.txt 2>/dev/null | wc -l | tr -d ' ')
  fi
fi

TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > STATE.md <<EOF
<!-- AUTO-GENERATED by .claude/hooks/update-state.sh — DO NOT HAND-EDIT.
     File is gitignored (B-003 Option E, cycle 8). Purely-local
     informational artifact; regenerated on each HEAD move. -->
# Repository State Snapshot

- **HEAD:** \`${HEAD_SHA}\` (${HEAD_SUBJECT})
- **Branch:** ${BRANCH}, ${AHEAD} ahead / ${BEHIND} behind \`origin/${BRANCH}\`
- **Working tree:** ${WT_STATE}
- **Smoke:** ${SMOKE_RESULT} (last run ${TIMESTAMP})
- **Pytest:** ${PYTEST_LINE}
- **Unread mailbox:** director=${UNREAD_DIR}, operator=${UNREAD_OP}
- **Updated:** ${TIMESTAMP} (after HEAD \`${HEAD_SHA}\`)
EOF

# Record HEAD so subsequent Bash calls skip regen unless HEAD moves again.
git rev-parse HEAD > "$MARKER"
