import os
import pickle
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# This scope allows us to upload videos to your channel, manage playlists, AND read advanced analytics
SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/yt-analytics.readonly"
]

def authenticate_youtube():
    """Handles OAuth 2.0 authentication and saves the token for future runs."""
    print("🔐 [PHASE D] Authenticating with YouTube...")
    creds = None
    
    # Check if we already have a saved token from a previous run
    if os.path.exists('token.pickle'):
        with open('token.pickle', 'rb') as token:
            creds = pickle.load(token)
            
    # If no valid credentials, let the user log in via browser
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("🔄 Refreshing expired Google token...")
            creds.refresh(Request())
        else:
            print("⚠️ First-time setup: Please check your browser to authorize the app...")
            # This requires client_secrets.json to be in your project folder!
            flow = InstalledAppFlow.from_client_secrets_file('client_secrets.json', SCOPES)
            creds = flow.run_local_server(port=0)
            
        # Save the credentials for the next run (Autonomy!)
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)

    return build('youtube', 'v3', credentials=creds)

def add_to_playlist(youtube, video_id, playlist_name):
    """Checks if a playlist exists. If not, creates it. Then adds the video to it."""
    # 1. Look for existing playlist
    playlists_response = youtube.playlists().list(
        part="snippet",
        mine=True,
        maxResults=50
    ).execute()
    
    playlist_id = None
    for item in playlists_response.get("items", []):
        if item["snippet"]["title"].lower() == playlist_name.lower():
            playlist_id = item["id"]
            break
            
    # 2. Create if not found
    if not playlist_id:
        print(f"📁 Creating new YouTube Playlist: {playlist_name}")
        create_response = youtube.playlists().insert(
            part="status,snippet",
            body={
                "snippet": {
                    "title": playlist_name,
                    "description": "Autogenerated series by the AI Short Pipeline."
                },
                "status": {
                    "privacyStatus": "public" 
                }
            }
        ).execute()
        playlist_id = create_response["id"]
        
    # 3. Add video to playlist
    print(f"🔗 Linking Video {video_id} to Playlist '{playlist_name}'...")
    youtube.playlistItems().insert(
        part="snippet",
        body={
            "snippet": {
                "playlistId": playlist_id,
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": video_id
                }
            }
        }
    ).execute()
    print("✅ Successfully routed into playlist!")

def upload_video(youtube, ctx: dict, publish_at=None):
    """Uploads the final .mp4 to YouTube as a Private Short and attaches a custom thumbnail."""
    video_file = ctx.get("final_video_path")
    script_data = ctx.get("script_data", {})
    # Strict YouTube character limits
    title = script_data.get("title", "Untitled Short")[:100]
    description = ctx.get("full_description", "")[:5000]
    tags = script_data.get("youtube_tags", [])
    thumbnail_file = ctx.get("final_thumbnail_path")
    playlist_name = script_data.get("playlist_category", "")
    
    print(f"🚀 [PHASE D] Preparing to upload: {video_file}")

    # Define the video metadata
    body = {
        "snippet": {
            "title": title,
            "description": description, 
            "tags": tags,
            "categoryId": "27", # 27 = Education. 
            # CRITICAL: YouTube explicitly greys out the "Subtitles" panel 
            # if a video is uploaded via the API without natively declaring 
            # its original default language matrix!
            "defaultLanguage": "en",
            "defaultAudioLanguage": "en"
        },
        "status": {
            # CRITICAL: Upload as private (required initially for scheduled videos)
            "privacyStatus": "private", 
            "madeForKids": False,
            "selfDeclaredMadeForKids": False
        }
    }
    
    if publish_at:
        body["status"]["publishAt"] = publish_at
        print(f"⏰ Scheduling video to go public automatically at: {publish_at}")

    # Load the physical file
    media = MediaFileUpload(video_file, chunksize=-1, resumable=True, mimetype="video/mp4")

    # Create the API request
    request = youtube.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=media
    )

    print("📤 Uploading to YouTube servers (this may take a moment)...")
    response = None
    try:
        while response is None:
            status, response = request.next_chunk()
            if status:
                print(f"   Upload progress: {int(status.progress() * 100)}%")

        print(f"✅ Upload Complete! Video ID: {response['id']}")
    except Exception as e:
        print(f"❌ FATAL ERROR during YouTube Upload: {e}")
        return None
    
    # --- NEW: Upload Thumbnail ---
    if thumbnail_file and os.path.exists(thumbnail_file):
        print(f"🖼️ Uploading custom thumbnail: {thumbnail_file}...")
        try:
            youtube.thumbnails().set(
                videoId=response['id'],
                media_body=MediaFileUpload(thumbnail_file, mimetype='image/jpeg')
            ).execute()
            print("✅ Custom thumbnail applied successfully!")
        except Exception as e:
            print(f"⚠️ Could not upload thumbnail (Note: you may need to verify your YouTube account for custom thumbnails). Error: {e}")

    # --- NEW: Automated Playlist Routing ---
    if playlist_name:
        try:
            add_to_playlist(youtube, response['id'], playlist_name)
        except Exception as e:
            print(f"⚠️ Could not add video to playlist. Error: {e}")

    ctx["youtube_video_id"] = response['id']
    return response['id']

# Optional testing block
if __name__ == "__main__":
    print("Run this through main.py to execute the full upload sequence!")

def get_bcp47_language(language_name):
    language_map = {
        "english": "en",
        "mandarin (simplified)": "zh-Hans",
        "mandarin": "zh-Hans",
        "korean": "ko",
        "japanese": "ja",
        "spanish (latin america)": "es-419",
        "spanish": "es",
        "hindi": "hi",
        "french": "fr",
        "german": "de",
        "arabic": "ar"
    }
    return language_map.get(language_name.lower().strip(), "en")

def upload_caption(youtube, video_id, language, srt_path):
    import os
    from googleapiclient.http import MediaFileUpload
    
    if not os.path.exists(srt_path):
        print(f"⚠️ Caption file {srt_path} not found. Skipping upload.")
        return
        
    bcp47_lang = get_bcp47_language(language)
    print(f"🌍 [PHASE D] Uploading '{language}' ({bcp47_lang}) Custom Subtitles for video {video_id}...")
    
    try:
        insert_request = youtube.captions().insert(
            part="snippet",
            body={
                "snippet": {
                    "videoId": video_id,
                    "language": bcp47_lang,
                    "name": f"{language} (Auto-Translated by AI)",
                    "isDraft": False
                }
            },
            media_body=MediaFileUpload(srt_path, mimetype='application/x-subrip')
        )
        response = insert_request.execute()
        print(f"✅ Success! True-Synced '{language}' Subtitles attached to the video API!")
        return response
    except Exception as e:
        print(f"❌ Error uploading customized {language} subtitles: {e}")

def upload_localizations(youtube, video_id, language, title, description):
    """
    Automatically adds a translated Title and Description to the video's Localization metadata.
    This ensures that foreign viewers see the video natively in their language on their YouTube feed.
    """
    bcp47_lang = get_bcp47_language(language)
    print(f"🌍 [PHASE D] Injecting '{language}' translated Titles & Descriptions into Master Video...")
    
    try:
        # Fetch current localizations so we don't wipe existing ones
        request = youtube.videos().list(
            part="snippet,localizations",
            id=video_id
        )
        response = request.execute()
        
        if not response["items"]:
            print(f"⚠️ Video {video_id} not found. Cannot add localizations.")
            return
            
        video = response["items"][0]
        
        # YouTube REQUIRES the snippet.defaultLanguage to be set before adding localizations
        if "defaultLanguage" not in video["snippet"]:
            video["snippet"]["defaultLanguage"] = "en"
            
        localizations = video.get("localizations", {})
        
        # Inject the new translation
        localizations[bcp47_lang] = {
            "title": title[:100], # YouTube max title length is 100 characters
            "description": description
        }
        
        video["localizations"] = localizations
        
        # Push the update back to YouTube
        update_request = youtube.videos().update(
            part="snippet,localizations",
            body={
                "id": video_id,
                "snippet": video["snippet"],
                "localizations": video["localizations"]
            }
        )
        update_response = update_request.execute()
        print(f"✅ Success! YouTube's global search engine now natively indexes the '{language}' translation!")
        return update_response
        
    except Exception as e:
        print(f"❌ Error uploading localizations for {language}: {e}")

