// Consolidated stage name → Tailwind text color map.
// This is the canonical 27-key superset; Notes.tsx and GenerationPanel.tsx
// both import from here so they stay in sync.
export const stageColors: Record<string, string> = {
  STYLE: 'text-purple-400',
  AUDIO: 'text-blue-400',
  SCENE: 'text-editorial-brass',
  DECOMPOSE: 'text-cyan-400',
  DIALOGUE: 'text-pink-400',
  GENERATE: 'text-yellow-400',
  VIDEO: 'text-orange-400',
  VALIDATED: 'text-editorial-ready',
  IDENTITY_FAIL: 'text-editorial-curtain',
  RETRY: 'text-editorial-warn',
  ASSEMBLY: 'text-indigo-400',
  COMPLETE: 'text-editorial-ready',
  DONE: 'text-editorial-ready',
  ERROR: 'text-editorial-curtain',
  CANCELLED: 'text-editorial-ivory-mute',
  WARNING: 'text-editorial-warn',
  KEYFRAME: 'text-yellow-400',
  KEYFRAME_READY: 'text-editorial-ready',
  KEYFRAME_REVIEW: 'text-editorial-brass',
  MOTION: 'text-orange-400',
  MOTION_READY: 'text-editorial-ready',
  PERFORMANCE: 'text-pink-400',
  REVIEW: 'text-editorial-brass',
  PLAN_REVIEW: 'text-cyan-400',
  DIRECTOR: 'text-purple-400',
  SHOT_FAILED: 'text-editorial-curtain',
  PAUSED: 'text-editorial-warn',
  RESUMED: 'text-editorial-ready',
}
